### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by benistary** [wtsnz/obs-ios-camera-source#75]
Hi, i don't know where to write about this issue, because it is about the ios app.

Recently I have updated app to version 3.2.2-104 and I saw that there is new functionality - remote control. But when I try to access the url via browser I get error. It seems that server is not running. I tested it on Iphone 12 mini,  ios version 15.1

![FC68952E-FC0D-492B-AF70-A596CCB0331A](https://user-images.githubusercontent.com/26891613/143321115-dfcbe39f-24db-442a-9e68-8c402bdfc40b.png)
![12228011-9CDB-4ADF-B552-BF21155F9F2D](https://user-images.githubusercontent.com/26891613/143321109-796762b6-df02-4ee3-99ab-3b687b3403c1.png)

If this will work, then this app will be even more amazing. ❤️

**Comment by wes-nz** [comment]
Hi,

We are aware of an issue. Try to turn it off, restart the app and turn it back on.

Let me know if it works.

**Comment by benistary** [comment]
Restart didn't work. But I have figured it out.

App uses IP in IPv6 format (device ip) which does not open. But I went to wifi settings and copied ipv4 ip of device, for example `http://192.168.0.206:8888/` and it works. I opened it on my mac. ❤️ 

![IMG_9761](https://user-images.githubusercontent.com/26891613/143413981-d9cfeb17-8b74-4b05-aa72-f135afa3e172.PNG)
![IMG_9762](https://user-images.githubusercontent.com/26891613/143414006-d86f3612-459a-4947-8eab-9b65758513f2.PNG)
![IMG_9763](https://user-images.githubusercontent.com/26891613/143414008-41887a58-27a3-4649-ac21-a15dfad11b9c.PNG)
![image](https://user-images.githubusercontent.com/26891613/143414270-57afdc9e-f758-4024-b863-2df811d2791c.png)

**Comment by wes-nz** [comment]
Awesome thanks for the update. We will check if there is a way to get the IPv4 over IPv6 when both are available.

**Comment by eric** [comment]
Do you have an estimate for how soon the new update will happen?

**Comment by wes-nz** [comment]
I will submit a new version to the App Store today. Sorry for the delay, we both have been unable to work last week.

**Comment by wes-nz** [comment]
Unfortunately the app got rejected by Apple just before we shut down for Christmas. We plan on fixing the issue related to the rejection this week. Hopefully by next week it will be out.

**Comment by wes-nz** [comment]
@benistary We released a new version fixing the bug. I will close the issue for now. Feel free to re-open if needed.

**Comment by eric** [comment]
I’m still seeing this issue. 

Steps to reproduce:
1. Open app
2. Connect remotely
3. Put phone to sleep
4. Wake phone (app is running again)
5. Try to connect remotely

At this point I get a connection refused.

**Comment by wes-nz** [comment]
You're right @eric there is a bug there. I'll create a new issue for that specific problem.
